In [2]:
import yfinance as yf 
import pandas as pd 
import matplotlib.pyplot as plt

In [22]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#Get historical data for sugar#11
sugar = yf.Ticker('SB=F')
df_sugar = sugar.history(period="6y") #Fetch last 6 years of sugar data 

#display the first few rows
display(df_sugar.head())

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-07-06 00:00:00-04:00,12.20,12.27,11.90,11.93,43237,0.0,0.0
2020-07-07 00:00:00-04:00,11.88,12.23,11.78,12.18,45004,0.0,0.0
2020-07-08 00:00:00-04:00,12.14,12.29,11.97,12.08,55011,0.0,0.0
2020-07-09 00:00:00-04:00,12.11,12.15,11.82,11.84,58010,0.0,0.0
2020-07-10 00:00:00-04:00,11.81,11.93,11.68,11.76,55821,0.0,0.0

In [27]:
#getting multiple commodities at once
commodity_tickers = {
    'Sugar': 'SB=F',
    'Coffee': 'KC=F',
    'Cocoa': 'CC=F',
    'Cotton': 'CT=F',
    'Wheat': 'ZW=F',
    'Corn': 'ZC=F',
    'Soybeans': 'ZS=F',
}

#Fetch historical data 
commodity_data ={}
for name, ticker in commodity_tickers.items():
    commodity_data[name] = yf.Ticker(ticker).history(period="6y")["Close"]

#convert to data frame 
df_commodities = pd.DataFrame(commodity_data)

print(df_commodities.shape)
display(df_commodities.head())

(1509, 7)

,Sugar,Coffee,Cocoa,Cotton,Wheat,Corn,Soybeans
Date,,,,,,,
2020-07-06 00:00:00-04:00,11.93,97.199997,2187.0,63.070000,489.50,346.50,898.50
2020-07-07 00:00:00-04:00,12.18,99.250000,2217.0,63.240002,492.25,345.00,895.25
2020-07-08 00:00:00-04:00,12.08,98.949997,2221.0,64.660004,517.50,348.25,894.75
2020-07-09 00:00:00-04:00,11.84,97.699997,2267.0,63.340000,526.25,351.25,898.25
2020-07-10 00:00:00-04:00,11.76,96.150002,2278.0,64.709999,535.75,340.50,891.50

In [30]:
#create a simple vissualisation of the data 

import plotly.express as px
#convert index in column for plotly compatibility
df_commodities_reset = df_commodities.reset_index()

#create interactive plotly line chart 
fig = px.line(
    df_commodities_reset, x='Date', y=df_commodities_reset.columns[1:],
    title='Commodity Prices Over Time',
    labels ={'value': 'Price(USD)', 'Date': 'Date'},  
    template='plotly_white'   
)
#Show the interactive plot
fig.show()

#video to help me https://www.youtube.com/watch?v=eGWjRwqnI7E&t=200s